on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Inso CLI
        uses: kong/setup-inso@v2
        with:
          inso-version: 11.4.0
          
      - name: running the account service 
        run: docker compose up -d
        
      - name: Lint API Specification
        run: INSO_SPEC_ID=$(awk '/spc_/{print $2}' api/accounts-service.yaml) ; inso lint spec -w api/accounts-service.yaml $INSO_SPEC_ID
      - name: Check if server is up
        run: |
          docker ps; curl --fail http://localhost:8081/health 

      - name: Run API Tests
        run: INSO_SPEC_ID=$(awk '/spc_/{print $2}' api/accounts-service.yaml); inso run test -w api/accounts-service.yaml $INSO_SPEC_ID "Accounts API Test Suite" --env "Dev - OpenAPI env localhost:8081"

